
server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wms
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: p0o9i8u7y6
#    url: jdbc:mysql://localhost:3306/wms02?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: p0o9i8u7y6


Logging:
  level:
    com.wms: debug